name:                pandoc-metaparsing
version:             0.1.0.0
github:              "despresc/pandoc-metaparsing"
license:             MIT
author:              Christian Despres
maintainer:          Christian Despres <christian.j.j.despres@gmail.com>
copyright:           Copyright (C) 2019 Christian Despres

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/despresc/pandoc-metaparsing#readme>

dependencies:
- base >= 4.7 && < 5
- pandoc-types
- mtl
- text
- containers
- hspec

library:
  source-dirs: lib

tests:
  pandoc-metaparsing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-metaparsing
