name:                pandoc-metaparsing
version:             0.1.0.0
github:              "despresc/pandoc-metaparsing"
license:             MIT
author:              Christian Despres
maintainer:          Christian Despres <christian.j.j.despres@gmail.com>
copyright:           Copyright (C) 2019 Christian Despres

extra-source-files:
- README.md

synopsis:            Parsers for Pandoc metadata
category:            Text

description:         Please see the README on GitHub at <https://github.com/despresc/pandoc-metaparsing#readme>

dependencies:
- base >= 4.7 && < 5
- pandoc-types < 1.18
- mtl < 2.3
- text < 1.3
- containers < 0.7
- hspec < 2.8

library:
  source-dirs: lib

tests:
  pandoc-metaparsing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-metaparsing
