name:                pandoc-metaparsing
version:             0.1.0.0
github:              "githubuser/pandoc-metaparsing"
license:             MIT
author:              Christian Despres
maintainer:          Christian Despres <christian.despres1@gmail.com>
copyright:           "2019 Christian Despres"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/despresc/pandoc-metaparsing#readme>

dependencies:
- base >= 4.7 && < 5
- pandoc
- pandoc-types
- mtl
- text
- containers
- hspec

library:
  source-dirs: lib

tests:
  pandoc-metaparsing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-metaparsing
